import {test,expect} from '@playwright/test';
import {writeFileSync,mkdirSync} from 'node:fs';
test.use({screenshot:'off'});
test('measured normal scene and synthetic 24-animal renderer stay bounded and release resources',async({page})=>{
 test.setTimeout(110000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/?debug=1&wildlife=1');await page.waitForFunction(()=>window.m0?.state().ready);await page.locator('#resume').click();await page.locator('#resolution-quality').selectOption('balanced',{force:true});await page.getByRole('button',{name:'К животному',exact:true}).click();await page.waitForFunction(()=>m0.wildlife.state().instances.some(i=>i.lod===0));
 await page.evaluate(()=>m0.beginMeasurement());await page.waitForTimeout(20000);
 const normal=await page.evaluate(()=>({frames:m0.endMeasurement(),costs:m0.frameCosts(),wildlife:m0.wildlife.state(),render:m0.state().render}));
 const setup=await page.evaluate(async()=>{
  const [{createWildlifeRenderer},{fetchWildlifeArt},{WildlifeWorld},{FrameWorkBudget},{showcaseHeight},{frameBytes}]=await Promise.all([import('/src/runtime/wildlife/render.ts'),import('/src/runtime/wildlife/assets.ts'),import('/src/domain/wildlife/world.ts'),import('/src/runtime/startup.ts'),import('/src/domain/showcase.ts'),import('/src/network/wildlife-protocol.ts')]);
  const data=await (await fetch('/wildlife/content/showcase/bird.json')).json(),scene=m0.inspect().scene,eye=m0.state().player;
  m0.wildlife.dispose();const counts=()=>({skeletons:scene.skeletons.length,animatables:scene.animatables.length});const before=counts();
  const cell={id:'0:0',contentHash:data.identity.contentHash,sites:[],routes:[],obstacles:[],neighbors:[]};
  for(const species of ['woodland-bird','red-squirrel','roe-deer']){const source=data.cells.find(c=>c.sites.some(s=>s.species===species)),site=source.sites.find(s=>s.species===species);for(let i=0;i<8;i++){const id=`stress-${species}-${i}`,home={e:eye.e+(i%4)*.4,n:eye.n+4+Math.floor(i/4)*.6,h:showcaseHeight(eye.e,eye.n+4)+(species==='woodland-bird'?1:0)},offset={e:home.e-site.home.e,n:home.n-site.home.n,h:home.h-site.home.h},translate=p=>Object.fromEntries(['e','n','h'].map(k=>[k,p[k]+offset[k]])),routes=source.routes.filter(r=>site.allowedRoutes.includes(r.id)).map(r=>({...r,id:`${id}/${r.id}`,from:id,samples:r.samples.map(s=>({...s,point:translate(s.point)})),bounds:{min:translate(r.bounds.min),max:translate(r.bounds.max)}}));cell.sites.push({...site,id,home,cellId:cell.id,allowedRoutes:routes.map(r=>r.id)});cell.routes.push(...routes);}}
  data.cells=[cell];const world=new WildlifeWorld({content:data.identity,authorityEpoch:'synthetic-budget',seed:'budget',cells:new Map([[cell.id,cell]]),limits:data.limits,bird:data.bird}),observers=Array.from({length:6},(_,i)=>({...eye,id:`stress-player-${i}`,e:eye.e+70+i,h:eye.h,headingDeg:0,speedMps:0,running:false,observedAtMs:0})),env={totalGameHours:12,daylight01:1,precipitation01:0};world.advance({simMs:0,observers,environment:env});
  const renderer=createWildlifeRenderer(scene,data,()=>{},await fetchWildlifeArt());renderer.setQuality({wildlifeShadows:2,wildlifeDetails:6,wildlifeDistance:22});let time=0,peakLoads=0,peakDetails=0,maxBytes=0;const cpu=[];
  const subscription=scene.onBeforeRenderObservable.add(()=>{const start=performance.now();time+=Math.min(50,scene.getEngine().getDeltaTime());world.advance({simMs:time,observers,environment:env});const frame=world.snapshot();renderer.update(frame,time,{e:0,n:0},eye);renderer.prepare(new FrameWorkBudget(3,1));cpu.push(performance.now()-start);const s=renderer.stats();peakLoads=Math.max(peakLoads,s.assetLoads);peakDetails=Math.max(peakDetails,s.detailedSkeletons);maxBytes=Math.max(maxBytes,frameBytes(frame));});
  window.__wildlifeStress={stats:()=>renderer.stats(),finish:()=>{scene.onBeforeRenderObservable.remove(subscription);const result={renderer:renderer.stats(),core:world.stats(),peakLoads,peakDetails,maxBytes,cpu:[...cpu],before};renderer.dispose();world.dispose();return {...result,after:counts()};}};return {entities:world.stats().activeEntities};
 });expect(setup.entities).toBe(24);await page.waitForFunction(()=>__wildlifeStress.stats().meshes===24&&__wildlifeStress.stats().pending===0);await page.evaluate(()=>m0.beginMeasurement());await page.waitForTimeout(20000);
 const maximum=await page.evaluate(()=>({frames:m0.endMeasurement(),costs:m0.frameCosts(),stress:__wildlifeStress.finish(),render:m0.state().render,userAgent:navigator.userAgent}));expect(maximum.stress.peakLoads).toBeLessThanOrEqual(2);expect(maximum.stress.peakDetails).toBeLessThanOrEqual(6);expect(maximum.stress.maxBytes).toBeLessThanOrEqual(32768);expect(maximum.stress.after).toEqual(maximum.stress.before);expect(maximum.stress.renderer.assetErrors).toEqual([]);expect(errors).toEqual([]);
 mkdirSync('tmp',{recursive:true});writeFileSync('tmp/wildlife-performance.json',JSON.stringify({scope:'Windows Chrome WebGPU 1280x720 balanced; actual normal scene and explicitly synthetic 24 animals / 6 core observers; no mobile claim',normal,maximum},null,2));
});
