import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
const backend='webgpu',url=process.env.WORLD_URL??'http://127.0.0.1:4178/';
mkdirSync('qa/evidence',{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:false,args:['--disable-backgrounding-occluded-windows']});
const page=await browser.newPage({viewport:{width:1920,height:1080},deviceScaleFactor:1}),errors=[],report={backend,url,checks:[],pois:[],errors};
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'||(m.type()==='warning'&&/invalid|error|index count of 0/i.test(m.text())))errors.push(m.text().slice(0,1800));});
const quantile=(a,p)=>[...a].sort((x,y)=>x-y)[Math.floor(a.length*p)];const summarise=a=>({count:a.length,median:quantile(a,.5),p95:quantile(a,.95),p99:quantile(a,.99),max:Math.max(...a)});
const state=()=>page.evaluate(()=>oldForest.state());const settle=()=>page.waitForFunction(()=>{const s=oldForest.state();return s.world.pending===0&&s.world.terrain.preparing===0&&s.world.forest.batchQueue===0;},{},{timeout:45000});
try{
 const start=Date.now();await page.goto(url+'?debug=1&renderer='+backend,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.oldForest?.state().ready||document.querySelector('#pause-title')?.textContent==='Не удалось открыть лес',{},{timeout:45000});assert.ok(await page.evaluate(()=>window.oldForest?.state().ready),await page.locator('#pause-description').innerText());report.coldReadyMs=Date.now()-start;await page.locator('#resume').click();await settle();report.initial=await state();const shaderCoverage=await page.evaluate(()=>oldForest.inspect().scene.getActiveMeshes().data.filter(m=>m?.name.startsWith('world-far')).every(m=>(m.subMeshes[0].effect??m.material.getEffect())?._fragmentSourceCode?.includes('worldLayer')));assert.ok(shaderCoverage,'Parent material retains its cutout shader after asset prewarm');report.checks.push('cold startup, parent cutout shader');
 await page.keyboard.down('KeyW');await page.keyboard.down('ShiftLeft');await page.waitForTimeout(3000);await page.keyboard.up('ShiftLeft');await page.keyboard.up('KeyW');let s=await state();assert.ok(s.player.e>535,'Walked through tunnel');assert.ok(s.camera.followError<.002);report.checks.push('tunnel passage, 15m/s, camera invariant');
 await page.keyboard.press('KeyM');await page.getByLabel('Места на карте').selectOption('bald_hill');await page.getByRole('button',{name:'Перейти к точке',exact:true}).click();await page.waitForFunction(()=>!oldForest.state().mapOpen,{},{timeout:45000});await settle();s=await state();assert.ok(Math.hypot(s.player.e-10000,s.player.n-33700)<101);assert.ok(s.camera.followError<.002);report.checks.push('map M, selected POI, prepared fast travel');
 const pois=await page.evaluate(()=>oldForest.pois());
 for(const poi of pois){await page.evaluate(id=>oldForest.travel(id),poi.id);await settle();await page.waitForTimeout(500);const s=await state();assert.ok(Math.hypot(s.player.e-poi.point[0],s.player.n-poi.point[1])<101,poi.id+' near POI');assert.ok(s.camera.followError<.002,poi.id+' camera');assert.ok(s.world.terrain.patches<=110,'bounded patches');assert.equal(s.world.failures,0);
  const safety=await page.evaluate(()=>{const {world}=oldForest.inspect(),p=oldForest.state().player;return {water:world.data.waterDepth(p.e,p.n),clear:!world.blocked(p.e,p.n)};});assert.ok(safety.water<=.35,poi.id+' dry landing');assert.ok(safety.clear,poi.id+' clear landing');report.pois.push({id:poi.id,player:s.player,world:s.world,render:s.render,heap:s.heap});console.log('POI',poi.id,s.world.tiles,s.world.terrain.patches,s.world.forest.trees,s.render.gpuMs.toFixed(2));
  if(['old_man_willow','tom_house','short_fall','bald_hill'].includes(poi.id))await page.screenshot({path:`qa/evidence/world-${poi.id}-${backend}.png`});
 }
 await page.evaluate(()=>oldForest.teleport(1200,25800));await settle();await page.evaluate(()=>oldForest.setCamera(30,12,5.5));await page.screenshot({path:`qa/evidence/world-forest-${backend}.png`});
 await page.evaluate(()=>oldForest.beginMeasurement());await page.waitForTimeout(10000);const m=await page.evaluate(()=>oldForest.endMeasurement());report.stationary={frames:summarise(m.frames),cpu:summarise(m.cpu),gpu:summarise(m.gpu)};
 await page.keyboard.press('KeyM');await page.waitForTimeout(300);await page.screenshot({path:`qa/evidence/world-map-${backend}.png`});await page.keyboard.press('KeyM');assert.equal((await state()).mapOpen,false);report.checks.push('M closes map');
 assert.equal(errors.length,0,errors.join('\n'));report.final=await state();console.log('PASS',JSON.stringify({checks:report.checks,pois:report.pois.length,stationary:report.stationary,coldReadyMs:report.coldReadyMs}));
}catch(e){report.failure=String(e);console.log('FAIL',e);await page.screenshot({path:`tmp/world-failure-${backend}.png`});process.exitCode=1;}finally{writeFileSync(`qa/evidence/world-runtime-${backend}.json`,JSON.stringify(report,null,2)+'\n');await browser.close();}
