import type {RegionSession,WaterState} from '../domain/regions/session.ts';
import {alongRoute} from '../domain/regions/session.ts';
import type {RegionHunt} from '../domain/regions/hunt.ts';
import './region.css';
export function regionInterface(session:RegionSession,world:{data:{geo:{source:any}}},hunt:RegionHunt,actions:{interact:()=>void;resolve:(choice:'help'|'observe')=>void;water:(value:WaterState)=>void;save:()=>void;pause:(value:boolean)=>void}){
 const hud=document.createElement('section');hud.className='region-hud';hud.innerHTML='<button id="region-map-button">Карта · M</button><button id="region-action" hidden></button><p id="region-notice" role="status"></p>';document.body.append(hud);
 const action=hud.querySelector<HTMLButtonElement>('#region-action')!,notice=hud.querySelector<HTMLElement>('#region-notice')!;let until=0;const debug=new URLSearchParams(location.search).get('debug')==='1';
 const dialog=document.createElement('dialog');dialog.className='region-map';dialog.innerHTML='<header><h2>У Брендивинского моста</h2><button id="region-map-close" aria-label="Закрыть карту">Закрыть</button></header><div class="region-map-layout"><canvas width="700" height="700" aria-label="Карта региона, положение следопыта и лодок"></canvas><section><h3>Лазутчики</h3><p>Проследите путь южанина, гоблина и орка: каждый следующий опаснее. Иногда в лесу появляются волки и вороны. 1 — лук, 2 — меч, ЛКМ — атака, Ctrl — тихий шаг.</p><div id="region-hunt-journal"></div><h3>Путник</h3><p>У двора говорят о путнике, который оставил дорогу. Его история отдельна от дозора.</p><div id="region-journal"></div><p id="region-map-notice" role="status"></p><h3>Переправы</h3><p>Ищите лодки у пологих сходов к реке. Найденные места появятся на карте. Подойдите к лодке и нажмите E. На воде — WASD, E у берега — высадка.</p><label>Уровень воды <select id="region-water"><option value="low">Низкий</option><option value="normal">Обычный</option><option value="high">Высокий</option></select></label><p>На высокой воде брод закрыт.</p><button id="region-save">Сохранить</button><p class="muted">Сохранение в этом браузере, отдельно от других сцен.</p><a href="regions/brandywine-bridge/preview/region-viewer.html" target="_blank" rel="noopener">Подробная топографическая карта</a></section></div>';document.body.append(dialog);
 const talk=document.createElement('dialog');talk.className='region-talk';talk.innerHTML='<h2>Путник</h2><p id="traveller-speech"></p><button id="traveller-help">Предложить помощь</button><button id="traveller-observe">Выслушать и записать</button><button id="traveller-close">Пока уйти</button>';document.body.append(talk);
 const canvas=dialog.querySelector('canvas')!,ctx=canvas.getContext('2d')!,source=world.data.geo.source;
 const water=dialog.querySelector<HTMLSelectElement>('#region-water')!;
 if(!debug)dialog.querySelector('a')!.hidden=true;
 const show=(message:string)=>{notice.textContent=message;dialog.querySelector('#region-map-notice')!.textContent=message;until=performance.now()+9000;};
 const toggle=()=>{if(dialog.open)dialog.close();else{actions.pause(true);water.value=session.state.player.water;dialog.showModal();draw();}};
 dialog.addEventListener('close',()=>actions.pause(false));talk.addEventListener('close',()=>actions.pause(false));
 hud.querySelector<HTMLButtonElement>('#region-map-button')!.onclick=toggle;dialog.querySelector<HTMLButtonElement>('#region-map-close')!.onclick=()=>dialog.close();
 action.onclick=actions.interact;water.onchange=()=>{actions.water(water.value as WaterState);water.value=session.state.player.water;};dialog.querySelector<HTMLButtonElement>('#region-save')!.onclick=actions.save;
 for(const choice of ['help','observe'] as const)talk.querySelector<HTMLButtonElement>('#traveller-'+choice)!.onclick=()=>{actions.resolve(choice);talk.close();};talk.querySelector<HTMLButtonElement>('#traveller-close')!.onclick=()=>talk.close();
 // The map uses the same metric bounds and source polylines as terrain and navigation.
 const xy=(e:number,n:number)=>[(e-source.playBounds.minE)/4000*660+20,(source.playBounds.maxN-n)/4000*660+20];
 function line(points:number[][],color:string,width:number){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();points.forEach((p,i)=>{const [x,y]=xy(p[0],p[1]);i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.stroke();}
 function dot(e:number,n:number,color:string,size:number,label?:string){const [x,y]=xy(e,n);ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,size,0,Math.PI*2);ctx.fill();if(label){ctx.font='11px sans-serif';ctx.fillStyle='#f4edcb';ctx.fillText(label,x+7,y-5);}}
 function draw(){ctx.fillStyle='#26372b';ctx.fillRect(0,0,700,700);for(const f of source.forests){ctx.fillStyle='#3b5135';ctx.beginPath();f.polygon.forEach((p:number[],i:number)=>{const [x,y]=xy(p[0],p[1]);i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.closePath();ctx.fill();}for(const r of source.rivers)line(r.stations,'#709dad',Math.max(3,r.stations[0][3]/4000*660));for(const h of source.hedges)line(h.points,'#a1ad79',3);for(const e of source.topology.edges)if(e.kind!=='boat')line(e.points,e.kind==='path'?'#7b8161':'#c8b17a',e.kind==='path'?1:2);
  for(const p of source.pois)if(debug||session.state.knownPlaces.includes(p.id))dot(...p.point as [number,number],'#d8c692',2.5,p.name);for(const b of session.state.boats)if(debug||session.state.knownPlaces.includes(b.id))dot(b.e,b.n,'#edbd62',4);dot(session.state.player.e,session.state.player.n,'#fff',6,'Вы');
  for(const id of hunt.state.tracks){const clue=hunt.clues.find(c=>c.id===id)!;dot(clue.e,clue.n,'#cde091',4,clue.label);}
  const e=session.state.encounter;if(e.clues.includes('tracks')){const p=alongRoute(e.route,30);dot(p.e,p.n,'#cde091',4,'Следы путника');}
  dialog.querySelector<HTMLElement>('#region-hunt-journal')!.textContent=hunt.state.completed?'Все трое лазутчиков обезврежены.':`${hunt.downCount} из ${hunt.state.scouts.length} лазутчиков остановлены. ${hunt.nextClue?'Следующее место поиска: '+hunt.nextClue.label+'.':'Следы прочитаны. Ищите патрули у обзорного плеча и на лесных тропах.'}`;
  const journal=dialog.querySelector<HTMLElement>('#region-journal')!;journal.replaceChildren();for(const text of [...e.clues.map(c=>c==='testimony'?'Свидетельство: путник ушёл от двора по боковой тропе.':'Следы: один человек, ровный шаг, следов борьбы нет.'),...(e.outcome?[e.outcome]:[])]){const p=document.createElement('p');p.textContent=text;journal.append(p);}
 }
 return {show,toggle,draw,talk(){const truth=session.state.encounter.truth;talk.querySelector('#traveller-speech')!.textContent={lodging:'«Я искал тихое место у рощи, но, кажется, лучше вернуться к постоялому двору. Покажете дорогу?»',help:'«Мой спутник ушёл к заводи. Я ищу его с утра и выбился из сил. Не оставите немного припасов и весть на постоялом дворе?»',scouting:'«Проверяю, можно ли доставить весть через нижнюю переправу, если ворота закроют. Мне нужен путь, а не ссора». '}[truth];actions.pause(true);talk.showModal();},update(prompt:string){action.hidden=!prompt;action.textContent=prompt?'E · '+prompt:'';if(performance.now()>until)notice.textContent='';if(dialog.open)draw();},dispose(){hud.remove();dialog.remove();talk.remove();}};
}
